title: Ashram Portfolio
logo : images/arsh.png
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

